### ISSUE TITLE
New Project Specs

### ISSUE THREAD

**Issue by rupaheizu** [hkzpjt/hkzpjt#6]
From integrating Illuminate components in the last few days, it's beginning to turn that the project is going to be tightly coupled. And I don't want this. To make things worse, I'm obligated to check the `laravel/framework` repository everyone now and then to check for the latest changes and applying them to the code base.

So, I've decided to use less overhead and start from scratch in making usable components for the project. Instead of utilizing Illuminate components, the project will begin to use Symfony components while having some folder structure of Laravel 5.

The project also needs some testing. By the time routing goes into play, testing can be started.

Here's the current to-do list
* Utilize Symfony 3 Components
* Implement DotEnv & Routing
* Implement Code Coverage Testing

**Comment by srph** [comment]
Might be off-topic. Anyway, I find ```cartalyst/sentry``` bloated badly designed.

**Comment by rupaheizu** [comment]
Will be removing that, but thanks for the notifying me. I've decided to make an in-house authentication. It may sound a lot of work but also utilizing a 3rd party for reference and contingency.

**Comment by rupaheizu** [comment]
Unfortunately, getting to abstract the whole Symfony verbosity is quite a lot of work. And I'm still torn whether or not to return Illuminate components into play. It's just me.

**Comment by srph** [comment]
Not every component is that tightly coupled to Laravel itself, right? Like, switch to Symfony's Container, but keep other Illuminate components if they suffice.

**Comment by rupaheizu** [comment]
The Foundation which makes everything works is. The Illuminate package is already deprecated.
